version: "3.8"

services:
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app/backend
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=versimplesecretkey

  frontend:
    build: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/app/frontend
    ports:
      - 3000:3000
