# Generated by Django 3.2.9 on 2021-11-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211109_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_time',
        ),
    ]
