# Generated by Django 3.2.9 on 2021-11-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_time']},
        ),
    ]
