# Generated by Django 3.2.9 on 2021-11-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewer',
            options={'ordering': ['-viewed_time']},
        ),
    ]
