# Generated by Django 3.2.9 on 2021-11-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='This show the user is verified and have the blue tick or not.', verbose_name='Is verified'),
        ),
    ]
