# Generated by Django 3.2.9 on 2021-11-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='male', max_length=100, no_check_for_status=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/users/default.jpg', upload_to=users.models.get_image_upload_to)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, max_length=150, null=True)),
                ('similar_account_suggestions', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
