# Generated by Django 3.2.9 on 2021-11-07 10:44

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211105_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Male', max_length=100, no_check_for_status=True, null=True),
        ),
    ]
