# Generated by Django 3.2.9 on 2021-11-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211107_1903'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='following',
            name='unique_followers',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user',
            new_name='follower_user',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='followed_time',
            new_name='following_time',
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('follower_user', 'following_user'), name='unique_followers'),
        ),
    ]
